name: Webhooks CD

on:
  push:
    branches: [main]

permissions:
  contents: read
  packages: write

jobs:
  ci:
    name: "Continuous Delivery"
    uses: ./.github/workflows/reusable-ci.yml
    with:
      publish-to-github: true
      publish-to-nuget: false
      upload-codecov: true
    secrets: inherit


