name: Webhooks PR Build

on:
  pull_request:
    branches: [main]

permissions:
  contents: read
  packages: read

jobs:
  ci:
    uses: ./.github/workflows/reusable-ci.yml
    with:
      publish-to-github: false
      publish-to-nuget: false
      upload-codecov: false


