name: Release Workflow

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  ci:
    uses: ./.github/workflows/reusable-ci.yml
    with:
      publish-to-github: true
      publish-to-nuget: true
      upload-codecov: true
    secrets: inherit


